### ISSUE TITLE
Cannot find module fs

### ISSUE THREAD

**Issue by jimmbraddock** [polenz/resource-deployer-example#1]
Hello! I'm newbie in javascript and node js, help please.
I cloned repository and followed README. Specially I reinstalled node js and downloaded the 4.4.7 version. I'm using windows. Then executed `npm i` and `grunt auto-build`. When I try click to "create new diagram", then getting error 

> Cannot find module 'fs'

Error appears in 

> bpmn-modeler\node_modules\camunda-resource-deployer-js\lib\ResourceDeployer.js"

What could be wrong?

**Comment by polenz** [comment]
It should be fixed. There is no new release at the moment. Please link the camunda-resource-deployer-js into camunda-resource-deployer-js-example.
Please close this issue when the problem is solved for you.

**Comment by jimmbraddock** [comment]
Thanks.

**Comment by rodrigosaavedra** [comment]
@jimmbraddock hi , this problem still exist ?

thanks.

**Comment by jimmbraddock** [comment]
To be honest, I don't know, because not using camunda now, i.e the problem is disappeared for me. If the problem still actual for you, that may reopen issue.

**Comment by arianerocha** [comment]
I had the same issue, this is what worked for me:

```
browserify: {
   options: {
      ....
      transform: [['brfs', { global: true }]]
      }
}
```
